### ISSUE TITLE
Add examples for using an Arduino Uno and Adafruit Motor Shield

### ISSUE THREAD

**Issue by dinoceros** [AlfredoElectronics/AlfredoConnect-Receive#2]

**Comment by jtberla** [comment]
LED control examples have been ported in 3e44386519d5e4f5f4da8bec51f9a62daa5656ba. Next step is to replicate default robot code for Uno type boards.

**Comment by dinoceros** [comment]
Robot examples for Uno and Adafruit Motor Shield v1 robots created, still need testing.

**Comment by dinoceros** [comment]
Four examples tested for Uno:
 * `LEDControlSerial.ino`: Turns on an LED when "W" is pressed, connected over hardware serial, typically USB.
 * `LEDControlBluetooth.ino`: Turns on an LED when "W" is pressed, connected over software serial, typically Bluetooth.
 * `DefaultArcadeBotKeyboard.ino`: Runs motors on an Adafruit Motor Shield v1 in arcade drive, controlled using WASD on the keyboard.
 * `DefaultArcadeBotGamepad.ino`: Runs motors on an Adafruit Motor Shield v1 in arcade drive, controlled using a gamepad.
